trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    robot --output output.xml --report report.html --log log.html first_smoke_suite/
  displayName: 'Run Robot Framework tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Robot'
    testResultsFiles: '**/output.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Robot Framework Tests'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'RobotTestResults'
    publishLocation: 'Container'