trigger: none  # Körs manuellt

pool:
  vmImage: 'macOS-latest'

variables:
  DEVICE_NAME: 'Medium_Phone_API_36'
  TEST_SCRIPT: 'run_tests.sh'
  RESULTS_DIR: 'Results'

steps:
# Installera Python och Robot Framework
- script: |
    python3 -m pip install --upgrade pip
    pip3 install robotframework robotframework-appiumlibrary
  displayName: 'Install Python & Robot Framework'

# Installera Appium
- script: |
    npm install -g appium
  displayName: 'Install Appium globally'

#  Öppnar emulator, startar Appium server och kör script
- script: |
    chmod +x $TEST_SCRIPT
    ./$TEST_SCRIPT
  displayName: 'Run Robot Framework tests via run_tests.sh'
  workingDirectory: '$(Build.SourcesDirectory)'

# Publicerar testresultat
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'Results/*/output.xml'
    testRunTitle: 'Robot Framework Results'

# Publicera rapport som artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Results'
    ArtifactName: 'RobotTestReports'
    publishLocation: 'Container'